version: "2"
linters:
  enable:
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
    nakedret:
      max-func-lines: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
