defaults: &defaults
  docker:
    - image: circleci/golang:1.15
  resource_class: small

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test

  build:
    <<: *defaults
    steps:
      - checkout
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
            - promruval

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: make docker

  release:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run: |
          echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_LOGIN}" --password-stdin
          make release
workflows:
  version: 2
  promruval:
    jobs:
      - test
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
      - release:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
