name: Test release

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: ReleaseNotes
        run: make release_notes.md
      - name: Test
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --clean --release-notes release_notes.md
